server:
  port: 8080

spring:
  application:
    name: petistan
  datasource:
    url: jdbc:mysql://localhost:3306/petistan
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true



